zt:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&preferredTestQuery=select 1
    username: root
    password: 1qazWSX.159
file:
  rootPath: /upload
image:
  rootPath: /upload/images
swagger:
  enable: false